[project]
name = "fine-tuning-exam"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.5.0",
    "peft>=0.18.1",
    "ray[train]>=2.40.0",
    "torch>=2.9.1",
    "transformers>=4.57.5",
    "trl>=0.26.2",
]
