apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ray-common

resources:
  - volume-holder.yaml
  - dataset.yaml
  - working-tree.yaml
  - model.yaml
  - output.yaml
  - pip-cache.yaml
