apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray-working-tree-pvc
  labels:
    app.kubernetes.io/name: ray-working-tree
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: ray-common
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-ai
  resources:
    requests:
      storage: 5Gi
