apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray-train-scripts-pvc
  labels:
    app.kubernetes.io/name: ray-train-scripts
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: ray-train
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-ai
  resources:
    requests:
      storage: 5Gi
